packages:
  - "backend"
  - "frontend-main"
  - "frontend-admin"
  - "shared"
allowBuilds:
  "@scarf/scarf": true
  esbuild: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
minimumReleaseAge: 4320
strictDepBuilds: true
