version: '3.9'

services:
  db:
    image: pgvector/pgvector:pg16-trixie
    container_name: crema-db
    restart: always
    env_file: .env
    environment:
      # Forzamos a que use la ruta estándar de Docker
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      # Mapeo de puerto PostgreSQL al host
      - "5432:5432"
    volumes:
      # Mapeamos nuestra carpeta local a esa misma ruta interna
      - ./postgres-data:/var/lib/postgresql/data/pgdata   # Persistencia de la base de datos
      - ./db/init:/docker-entrypoint-initdb.d             # Scripts automáticos (solo primera vez)
    networks:
      - crema-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER} -d $${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: crema-redis
    restart: always
    networks:
      - crema-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s

networks:
  crema-net:
    driver: bridge